### ISSUE TITLE
Please follow Semantic Versioning

### ISSUE THREAD

**Issue by cbauer10** [valpackett/SwiftCBOR#91]
It would be really appreciated if semantic version was followed in this repo.  Both 0.4.5 and 0.4.6 included breaking changes and it is cumbersome to have to manually update this library and keep track of what it is doing instead of consuming what should have been non breaking changes.

**Comment by hamchapman** [comment]
I understand the frustration in general and apologies for any issues that you've run into because of the nature of these releases. 

I'd be curious as to what you were doing that made 0.4.6 a breaking change for you?

You may well already know this but strictly speaking semantic versioning specifies the following:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

https://semver.org/#spec-item-4

**Comment by cbauer10** [comment]
We are implementing the CBOREncodable Protocol so when a method is changed, like what happened in 0.4.5 and 0.4.6, our code is no longer able to compile.

Yes I realize the legal reason as to why you are keeping this at 0.x.x, but it would still be appreciated if some semblance of semantic versioning was followed to where incrementing the bug fix number is not a breaking change.
